#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

ynh_backup "$data_dir"
ynh_backup "/var/lib/bind"
ynh_backup "/var/cache/bind"

ynh_backup "/etc/bind/named.conf.options"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app-regen-named-conf.service"
ynh_backup "/etc/systemd/system/$app-regen-named-conf.path"
ynh_backup "/etc/systemd/system/$app-dnstap.service"
ynh_backup "/etc/systemd/system/$app-dnstap.socket"

ynh_backup "/etc/nftables.d/${app}.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/var/log/$app/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
