#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

ynh_safe_rm "/etc/systemd/system/$app-dnstap.socket"
ynh_config_remove_systemd "$app-dnstap"
ynh_safe_rm "/etc/systemd/system/$app-regen-named-conf.path"
ynh_config_remove_systemd "$app-regen-named-conf"
ynh_config_remove_systemd

ynh_safe_rm "/etc/nftables.d/${app}.conf"

ynh_config_remove_logrotate

ynh_config_remove_nginx

_rm_config_named

ynh_systemctl --service="nftables" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
