#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

mv "/etc/bind/named.conf.options" "/etc/bind/named.conf.options.orig"
ynh_restore "/etc/bind/named.conf.options"
chown -R "bind:bind" "/etc/bind/named.conf.options"
chmod ug+rwX "/etc/bind/named.conf.options"

#=================================================
# RESTORE THE DATA DIRS
#=================================================
ynh_script_progression "Restoring the data directories..."

# Backup data directories
ynh_restore "$data_dir"
ynh_restore "/var/lib/bind"
ynh_restore "/var/cache/bind"

chown -R "bind:bind" "/var/lib/bind" "/var/cache/bind"
chmod ug+rwX "/var/lib/bind" "/var/cache/bind"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-dnstap.socket"
ynh_restore "/etc/systemd/system/$app-dnstap.service"
ynh_restore "/etc/systemd/system/$app-regen-named-conf.path"
ynh_restore "/etc/systemd/system/$app-regen-named-conf.service"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
systemctl enable "$app-regen-named-conf.path" --quiet
systemctl enable "$app-dnstap.socket" --quiet

yunohost service add "$app" --description="Dynette gunicorn daemon" --log="/var/log/$app/$app.log"

ynh_restore "/etc/nftables.d/${app}.conf"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"
chown -R "$app:$app" "/var/log/$app/"
chmod ug+rwX "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="named" --action="start"
ynh_systemctl --service="$app" --action="start"
systemctl start "$app-regen-named-conf.path"
systemctl start "$app-dnstap.socket"

ynh_systemctl --service=nginx --action=reload
ynh_systemctl --service="nftables" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
